---
title: "inflation rate"
author: "Quang VU"
date: '2022-07-03'
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: yes
      smooth_scroll: no
    code_folding: show
    code_dowload: yes
    theme: flatly
    highlight: zenburn
  pdf_document:
    toc: yes
    toc_depth: '2'
---

```{r setup, include=FALSE}
#library load
library(ggflags)
library(tidyverse)
library(showtext)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggbump)
library(janitor)
library(viridis)
library(rvest)
library(sf)
library(countrycode)
library(glue)
library(ggtext)
library(png)
```


```{r}
img <- png::readPNG("C:/Users/Admin/Downloads/eu flag.png")
i1 <- grid::rasterGrob(img, interpolate = T)
```

```{r cars}
# setting up text font
showtext_auto()

#sysfonts::font_families_google()

font_add_google("Roboto", "Roboto")
font_add_google("Pacifico", "Pacifico")
font_add_google("Roboto Mono", "Roboto")
font_add_google("Bitter", "Bitter")


sf::sf_use_s2(FALSE)



```


```{r pressure, echo=FALSE}
# scarp data from  trading economics with rvest 

page <- read_html("https://tradingeconomics.com/country-list/inflation-rate?continent=europe")
page %>% 
  html_table() %>% 
  .[[1]] %>% 
  clean_names() %>% 
  mutate(country_code = c(countrycode(country,
                                      origin = "country.name",
                                      destination = "genc2c"))) %>%
  select(country, country_code, last)  -> data 
    
data
```




```{r}

eu_geo <- rnaturalearthdata::countries50 %>% 
  st_as_sf() %>% 
  st_crop(xmin = -10, xmax = 40, ymin = 33, ymax = 73) %>% 
  filter(name %in% data$country) %>%  
  left_join(data, by = c("name" = "country"))

eu_geo
```



```{r}
### data for ploting 

countries <-  c("CH","NO","FR","FI","IT","DE","NL","GB","ES","GR","RU","UA")

st_geometry(eu_geo) %>% 
  st_point_on_surface() %>% 
  st_coordinates() %>% 
  as_tibble() %>% 
  bind_cols(eu_geo) %>% 
  rename(inflation_rate = last) %>% 
  filter(country_code %in% countries) %>% 
  mutate(rank = rank(inflation_rate)) %>% 
  arrange(desc(rank)) %>% 
  mutate(y_rank = rev(seq(min(35:70),max(35:70),len = length(countries)))) %>% 
  mutate(country_code = str_to_lower(country_code)) %>% 
 arrange(desc(rank))-> data_plot

data_plot
```

```{r}
### title and subtitle 

x_rank <- 80
title <- glue("<span style='font-family: Bitter; color: #DA291C'><strong> Inflation Rate reported in several countries part of </strong></span>",
              "<span style='font-family: Bitter; color: #001489'><strong>Europe</strong></span>")

subtitle <- glue("Due to the conflict between ",
                 "<span style=' font-family: Roboto Mono; color: #0033A0'><strong>RUS</strong></span>",
                 "<span style=' font-family: Roboto Mono; color: #DA291C'><strong>SIA</strong></span>",
                 " and ",
                 "<span style=' font-family: Roboto Mono; color: #005BBB'><strong>UKRA</strong></span>",
                 "<span style=' font-family: Roboto Mono; color: #FFD500'><strong>INE</strong></span>",
  ", annual inflation in the eurozone’s 19 countries hit 8.6% in June, surging past the 8.1% recorded in May
  \nInflation is at its highest level since recordkeeping for the euro began in 1997.")
```


```{r}

ggplot() + 
  
  # creat map
  geom_sf(data = eu_geo ,
          size = .3,
          fill = "transparent",
          color = "#0033A0") +
  
  
  # Sigmoid from country to start of barchart
  geom_sigmoid(data = data_plot, 
               aes(x = X,
                   y = Y,
                   xend = x_rank ,
                   yend = y_rank,
                   group = country_code,
                   color = rank), 
               alpha = .6,
               smooth = 10,
               size = 1.3) +
  # flag
  
  geom_flag(
    data = data_plot, 
    aes(
      x = X,
      y = Y,
      country = country_code,
      size = 8
    )
  ) +
  
  
  # bar plot
  geom_segment(data = data_plot, 
               aes(x = x_rank ,
                   y = y_rank,
                   xend = x_rank  + inflation_rate,
                   yend = y_rank,
                   color = rank), alpha = .6, size = 1.3, 
               lineend = "round") +
  
  # Country text
  geom_text(data = data_plot,
            aes(x = x_rank, y = y_rank, label = geounit, color = rank),
            hjust = 1,
            vjust = 0.2,
            size = 3.5,
            nudge_y = .5,
            fontface='bold',
            family = "Roboto") +
  
  # Value text
  geom_text(data = data_plot,
            aes(x = x_rank  + inflation_rate,
                y = y_rank,
                label = paste0(inflation_rate,"%"),
                color = rank),
            hjust = 0,
            size = 4,
            nudge_x = .4,
            family = "Roboto") +
  
  coord_sf(clip = "off") +
  theme_void() +
  scale_color_gradient(high  = "#DA291C", low = "#002295") +
  
  # eu flag in top left 
  annotation_custom(i1,
                    ymin = 60, 
                    ymax = 75,
                    xmin = -15,
                    xmax = 5) +
  labs(
    title = title,
    subtitle = subtitle,
    caption = "Visualization by @nhatquanglhp • Data from Trading Economics | European Union statistics",)+
  
  theme(
    legend.position = "none",
    plot.title = element_markdown(size = 20),
    plot.subtitle = element_markdown(size = 9),
    plot.caption = element_text(family = "Pacifico", color = "#463886"),
    plot.margin = margin(r = 0.5, unit = "cm"),
  )
```


